language: r
sudo: false
dist: trusty
# cache: packages
latex: true
env:
  global:
    - _R_CHECK_TIMINGS_=0
    - _R_CHECK_TESTS_NLINES_=999
    - secure: "d0xff7hriQyReF4y3/iR5sHJlXocKNKcN6/Gi/r9Hxsfuh2Hx3fouQCMSPP+Oba6MDgEvAfryToAxcmaoZByQMwgevB0OBy5xkatj3oTHmhN5Nbk3jNXxXfA6P0Oqxaf7lXVZk2+Ly+PWnbgXn0uhjzdaZo0cWtVJ660ajS0x9Q="

jobs:
  include:
    - stage: check
      env: RCMDCHECK=TRUE
      addons:
        apt:
          packages:
           - libgmp-dev
           - libgsl0-dev
           - libgdal-dev # for sf
           - libproj-dev # for sf
           - libgeos-dev # for sf
           - libudunits2-dev # for sf
           - r-cran-dplyr
           - r-cran-stringi
           - r-cran-rcpp
           - r-cran-igraph
           - r-cran-xgboost

      before_install: R -q -e 'if (!requireNamespace("remotes", quietly = TRUE)) install.packages("remotes"); if (!requireNamespace("curl", quietly = TRUE)) install.packages("curl"); remotes::install_github("ropenscilabs/tic@fix-install-deps"); tic::prepare_all_stages(); tic::before_install()'
      warnings_are_errors: false
      before_script: R -q -e 'tic::before_script()'
      install: R -q -e 'tic::install()'
      script: R -q -e 'tic::script()'
      after_script: R -q -e 'tic::after_script()'
      before_deploy: R -q -e 'tic::before_deploy()'
      deploy:
         provider: script
         script: R -q -e 'tic::deploy()'
         on:
           all_branches: true

    - stage: Tutorial
      env: TUTORIAL=HTML
      addons:
        apt:
          packages:
           - libgmp-dev
           - libgsl0-dev
           - libgdal-dev # for sf
           - libproj-dev # for sf
           - libgeos-dev # for sf
           - libudunits2-dev # for sf
      latex: false
      pandoc_version: 2.3.1
      before_install:
        - R -q -e 'if (!requireNamespace("BiocManager")) install.packages("BiocManager"); if (!requireNamespace("genefilter")) BiocManager::install("genefilter")'
        - R -q -e 'install.packages("remotes"); remotes::install_github("ropenscilabs/tic"); tic::prepare_all_stages()'
      install: R -q -e 'tic::install()'
      script:  R -q -e 'tic::script()'
      after_script: R -q -e 'tic::after_script()'
      before_deploy: R -q -e 'tic::before_deploy()'
      deploy:
         provider: script
         script: R -q -e 'tic::deploy()'
         on:
           all_branches: true
