language: r
sudo: false
dist: trusty
cache: packages
env:
  global:
    - _R_CHECK_TIMINGS_=0
    - _R_CHECK_FORCE_SUGGESTS_=0  # no error if suggested packs are not avail
    - _R_CHECK_TESTS_NLINES_=999
    - secure: "d0xff7hriQyReF4y3/iR5sHJlXocKNKcN6/Gi/r9Hxsfuh2Hx3fouQCMSPP+Oba6MDgEvAfryToAxcmaoZByQMwgevB0OBy5xkatj3oTHmhN5Nbk3jNXxXfA6P0Oqxaf7lXVZk2+Ly+PWnbgXn0uhjzdaZo0cWtVJ660ajS0x9Q="
    - WARMUPPKGS='roxygen2 pander mlrMBO purrr cowplot sf mlbench mldr RWeka RWekajars knitr dplyr ggplot2 ranger randomForest kernlab igraph rjson rmarkdown xgboost xml2'

jobs:
  include:
    - stage: warmup
      env: RCMDCHECK=TRUE
      addons:
        apt:
          packages:
           - libgmp-dev
           - libgsl0-dev
           - libgdal-dev # for sf
           - libproj-dev # for sf
           - libgeos-dev # for sf
           - libudunits2-dev # for sf
      before_install: R -q -e 'install.packages("remotes"); remotes::install_github("ropenscilabs/tic"); tic::prepare_all_stages()'
      install: R -q -e 'tic::install()'
      script: true
      after_script: R -q -e 'tic::after_script()'
    - stage: check
      env: RCMDCHECK=TRUE
      addons:
        apt:
          packages:
           - libgmp-dev
           - libgsl0-dev
           - libgdal-dev # for sf
           - libproj-dev # for sf
           - libgeos-dev # for sf
           - libudunits2-dev # for sf
      before_install: R -q -e 'install.packages("remotes"); remotes::install_github("ropenscilabs/tic"); tic::prepare_all_stages()'
      warnings_are_errors: false
      before_script: R -q -e 'tic::before_script()'
      script: R -q -e 'tic::script()'
      after_script: R -q -e 'tic::after_script()'
      deploy:
         provider: script
         script: R -q -e 'tic::deploy()'
         on:
           all_branches: true

    - stage: Tutorial
      env: TUTORIAL=HTML
      addons:
        apt:
          packages:
           - libgmp-dev
           - libgsl0-dev
           - libmagick++-dev # for favicon
           - libgdal-dev # for sf
           - libproj-dev # for sf
           - libgeos-dev # for sf
           - libudunits2-dev # for sf
      latex: false
      pandoc_version: 2.2.1
      before_install: R -q -e 'install.packages("devtools"); devtools::install_github("pat-s/tic@rcmdcheck-build-args"); tic::prepare_all_stages()'
      install: R -q -e 'tic::install()'
      script:  R -q -e 'tic::script()'
      after_script: R -q -e 'tic::after_script()'
      before_deploy: R -q -e 'tic::before_deploy()'
      deploy:
         provider: script
         script: R -q -e 'tic::deploy()'
         on:
           all_branches: true

notifications:
  email:
    recipients:
      - bernd_bischl@gmx.net
  slack: mlr-org:DYNA3KIwcG9F4sQoeyTnPBhF#buildnotifications
on_success: change
on_failure: always
